#!/bin/bash

set -ueo pipefail

CURDIR=$(pwd)
PROJECT=${1:?Must specify a project name}

mkdir $PROJECT{,.git}

cd $PROJECT.git || exit
git init --bare
cd $CURDIR || exit

echo -e "#!/bin/bash\n\nGIT_WORK_TREE=$CURDIR/$PROJECT/ git checkout -f" > $CURDIR/$PROJECT.git/hooks/post-receive

chmod u+x $CURDIR/$PROJECT.git/hooks/post-receive
