#!/bin/bash

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) LIMIT
EOM
usage.sh "$USAGE" $@ && exit
#[ $# -lt 1 ] && $0 --help && exit

#requires SOME_PROGRAM || exit
#requires-file SOME_FILE || exit

limit=${1:-50}
output_file=du-inodes.txt


# Solution from
# https://askubuntu.com/questions/316027/find-directories-with-lots-of-files-in
# TODO: consider a better solution

# FAST
locate '' | sed 's|/[^/]*$|/|g' | sort | uniq -c | sort -n | tee "$output_file" | tail -$limit


# SLOW
#filesystem='/'
#sudo find $filesystem -xdev -printf '%h\n' | sort | uniq -c | sort -k 1 -n | tee "$output_file" | tail -$limit
