#!/bin/bash

# Turn on dual monitors if plugged in - breaks X sometimes?
xrandr --current | grep "VGA1 connected" > /dev/null
secondMonitor=$?
if [ -n "$secondMonitor" ]; then
	dualmon on &
else
	dualmon off &
fi
