#!/bin/bash

# Modified from http://unix.stackexchange.com/questions/34248/how-can-i-find-broken-symlinks

set -ueo pipefail

dir=${1:-.}
depth=${2:-}

if [ -z "$depth" ]; then
    find "$dir" -xtype l
else
    find "$dir" -maxdepth $depth -xtype l
fi
