#!/usr/bin/fish

# Poor man's bash -> fish converter
# Deps: perl

## TODO:
# - alias -> abbr
# - function() { ... } -> function <name>; bass <function-body> $argv; end

set bashfile $argv[1]

# HACK due to: https://github.com/fish-shell/fish-shell/issues/159
set tmpfile $bashfile.tmp
set fishfile $bashfile.fish

command cp $bashfile $tmpfile

# Remove comments
perl -pe 's/#.*$//s' -i $tmpfile

# Remove if statements
perl -0777 -pe 's/\s?if\s+.*\s+fi\s?//gs' -i $tmpfile

# Remove functions
perl -0777 -pe 's/\s?function\s+.*\s+}\s?//gs' -i $tmpfile

# Replace &&, ||
perl -0777 -pe 's/ &&/; and/gs' -i $tmpfile
perl -0777 -pe 's/ \|\|/; or/gs' -i $tmpfile

# Don't actually create aliases for now
function aliass;
	echo 'setting alias: '$argv[1];
end;
perl -0777 -pe 's/alias /aliass /gs' -i $tmpfile

command cp $tmpfile $fishfile
command rm $tmpfile
echo $fishfile
