#!/bin/bash

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) IP_ADDRESS
EOM
usage.sh "$USAGE" $@ && exit
[ $# -lt 1 ] && $0 --help && exit

ip=${1??Enter an IP address}


info=$(curl -s ipinfo.io/$ip | jq '.')
city=$(echo $info | jq -r '.city')
region=$(echo $info | jq -r '.region')
country=$(echo $info | jq -r '.country')
postal=$(echo $info | jq -r '.postal')
org=$(echo $info | jq -r '.org')

echo "$city, $region, $country ($postal) - $org"

# use echo to fix broken last char
# echo "$(curl -s ipinfo.io/$ip | jq '.')"
