#!/bin/bash

# Hack to convert GitHub-Flavored Markdown to HTML without
# using GitHub's API (works offline)
# Deps: ~/.gfm/{head.html,tail.html,subs.dat}, marked(npm)

CONFDIR="$HOME/.gfm"

if [[ $# -lt 1 ]]; then
	# no file specified - run on all markdown files
	files=*.md
else
	files="$@"
fi


for f in $files; do
	gfmfile="$1"
	shift

	#echo $gfmfile && continue
	[ ! -f "$gfmfile" ] && echo "File not found: $gfmfile" && continue

	htmlfile=$(echo $gfmfile | sed 's/\..*$/\.html/')
	cat "$CONFDIR/head.html" > $htmlfile

	# Replace title
	title=${gfmfile%.md}
	sed -i 's/<title><\/title>/<title>'$title'<\/title>/' $htmlfile

	html=$(marked $gfmfile)

	# http://stackoverflow.com/questions/10929453/bash-scripting-read-file-line-by-line
	while IFS='' read -r line || [[ -n $line ]]; do
		echo "sed: $line"
		html="`echo "$html" | sed 's,'"$line"',g'`"
	done < "$CONFDIR/subs.dat"

	echo $html >> $htmlfile
	cat "$CONFDIR/tail.html" >> $htmlfile

	echo "$htmlfile"
done
