#!/bin/bash

# Hack to convert GitHub-Flavored Markdown to HTML without
# using GitHub's API (works offline)

set -u

requires marked
requires-file ~/.gfm/{head.html,tail.html,subs.dat}

usage.sh "gfm [FILES]..." $@ && exit

CONFDIR="$HOME/.gfm"

if [[ $# -lt 1 ]]; then
	# no file specified - run on all markdown files
	files="*.md"
else
	files="$@"
fi


for f in $files; do
	gfmfile="$f"

	#echo $gfmfile && continue
	[ ! -f "$gfmfile" ] && echo "File not found: $gfmfile" && continue

	htmlfile="$gfmfile.html"
	cat "$CONFDIR/head.html" > "$htmlfile"

	# Replace title
	title=${gfmfile%.md}
	sed -i 's/<title><\/title>/<title>'"$title"'<\/title>/' "$htmlfile"

	html=$(marked "$gfmfile")

	# http://stackoverflow.com/questions/10929453/bash-scripting-read-file-line-by-line
	while IFS='' read -r line || [[ -n $line ]]; do
		dbg "sed: $line"
		html="`echo "$html" | sed 's,'"$line"',g'`"
	done < "$CONFDIR/subs.dat"

	echo "$html" >> "$htmlfile"
	cat "$CONFDIR/tail.html" >> "$htmlfile"

	echo "$htmlfile"
done
