#!/bin/bash

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) <branch name of backup>
EOM
usage.sh "$USAGE" $@ && exit
[ $# -lt 1 ] && $0 --help && exit

requires git-current-branch.sh || exit
#requires-file SOME_FILE || exit

backupBranch=${1??Enter a branch name to back up to}
curBranch=$(git-current-branch.sh)
git checkout -b $backupBranch
git checkout $curBranch
echo -e "\n\nBacked up $curBranch to $backupBranch"
