#!/usr/bin/zsh

set -ueo pipefail

USAGE="$(basename $0) [i3 STARTUP CONFIG FILE]\n\nDefault file is ~/.config/i3/startup if not specified"
usage.sh "$USAGE" $@ && exit

startupFile=${1:-~/.config/i3/startup}

while IFS='' read -r line || [[ -n $line ]]; do
	if [[ -n "$line" && "${line:0:1}" != '#' ]]; then
		echo "Running: $line"
		if [[ $line =~ "^include " ]]; then
			file=$(echo $line | cut -c9-)  # strip out include
			$0 $file
		else
			i3-msg "$line"
			if [[ $line =~ "^exec " ]]; then
				# wait when executing command
				#sleep 1
			else
			fi
				sleep 0.3
		fi
	else
		#echo "Skipping: $line"
	fi
done < $startupFile
