#!/usr/bin/zsh

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) [i3 STARTUP CONFIG FILE]

Default file is 'startup' in the ~/.config/i3 directory if not specified
EOM

usage.sh "$USAGE" $@ && exit

CONFIG_DIR=${CONFIG_DIR:-~/.config/i3}
startupFile=${1:-startup}

while IFS='' read -r line || [[ -n $line ]]; do
	if [[ -n "$line" && "${line:0:1}" != '#' ]]; then
		echo "Running: $line"
		if [[ $line =~ "^include " ]]; then
			file=$(echo $line | cut -c9-)  # strip out include
			$0 $file
		else
			i3-msg "$line"
			sleep 0.3
		fi
	else
		#echo "Skipping: $line"
	fi
done < $CONFIG_DIR/$startupFile
