#!/bin/bash

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) [FILENAME | URL]
EOM
usage.sh "$USAGE" $@ && exit
[ $# -lt 1 ] && $0 --help && exit

JS_MINIFIER=uglifyjs
CSS_MINIFIER=csso
JS_MINIFIER_ARGS="-m names"
FORCE=${FORCE-}   # force redownload / regeneration of files

requires err filesize filename-or-url $JS_MINIFIER || exit
#requires-file SOME_FILE || exit

filename=$(FORCE=$FORCE filename-or-url $1)

# Original
echo "# $filename"
echo "Original: $(filesize -h $filename)"

# Minified
ext=${filename##*.}
minified="${filename%.*}.min.$ext"

if [ "$ext" = "js" ]; then
	[[ $FORCE || ! -f $minified ]] && $JS_MINIFIER $JS_MINIFIER_ARGS $filename > $minified
elif [ "$ext" = "css" ]; then
	[[ $FORCE || ! -f $minified ]] && $CSS_MINIFIER $filename > $minified
else
	err "Extension is not js or css. It is $ext"
fi

echo "Minified: $(filesize -h $minified)"

# Minified+Gzipped
mingzipped="${filename%.*}.min.$ext.gz"
[[ $FORCE || ! -f $mingzipped ]] && gzip -c $minified > $mingzipped
echo "Min+Gzip: $(filesize -h $mingzipped)"

