#!/bin/bash

set -ueo pipefail

read -r -d '' USAGE << EOM || true
$(basename $0) [FILENAME | URL]
EOM
usage.sh "$USAGE" $@ && exit
[ $# -lt 1 ] && $0 --help && exit

MINIFIER=uglifyjs
MINIFIER_ARGS="-m names"
FORCE=${FORCE-}   # force redownload / regeneration of files

requires filesize $MINIFIER
#requires-file

url=$1

if [ -f $url ]; then
	filename=$url
else
	filename="${url##*/}"
	[[ $FORCE || ! -f $filename ]] && curl -sL $url > $filename
fi

echo "# $filename"
echo "Original: $(filesize -h $filename)"

minified="${filename%.*}.min.js"
[[ $FORCE || ! -f $minified ]] && $MINIFIER $MINIFIER_ARGS $filename > $minified
echo "Minified: $(filesize -h $minified)"

mingzipped="${filename%.*}.min.js.gz"
[[ $FORCE || ! -f $mingzipped ]] && gzip -c $minified > $mingzipped
echo "Min+Gzip: $(filesize -h $mingzipped)"
