#!/bin/bash

# npm_lazy wrapper (that automatically starts and shutsdown server)
# Deps: npm_lazy
# Requires: ~/.npm_lazy.config.js

set -u

if [[ -z `pgrep -f npm_lazy` ]]; then
	echo "Starting npm_lazy server..."
	nohup npm_lazy --config ~/.npm_lazy.config.js | tee /dev/null  &
	sleep 2
else
	echo "Using existing npm_lazy server..."
fi

config=~/.npm_lazy.config.js
[ -f $config ] || echo "Could not find config file: $config" || exit

local_registry=`grep externalUrl $config | awk '{print $2}' | tr -d "',"`

echo "Running npm command with local registry: $local_registry"
npm --registry $local_registry $@


## Make sure that server is shut down later and that only one background process
## to shut it down is running at a time
pid_file=$HOME/.tmp/npm-lazy-kill-later

# Kill old background process if any and remove file
if [ -f "$pid_file" ]; then
	old_pid=`cat "$pid_file"`
	pgrep $old_pid && kill $old_pid
	command rm "$pid_file"
fi

# Background process to shut down server later
{
	#notify.sh "Sleeping 30m"
	sleep $((60*30)) # shutdown after 30m
	#notify.sh "Killing npm_lazy server..."
	pgrep npm || pkill npm_lazy
	command rm $pid_file
} &

#echo "This pid: $$"
#echo "Background pid: $!"

# Keep track of sole background process
echo $! > $pid_file

# If planning to run npml as root, uncomment this line
# chown boris $pid_file
