#!/bin/bash

# Simple stats script

SLEEPTIME=$1
[ -z $1 ] && SLEEPTIME=10

while true; do
	LOAD=`uptime`
	#CPU=`top -n1 | head -6 | tail -n +2 | head -2`

	# Adapted from: http://superuser.com/questions/609949/what-are-the-methods-available-to-get-the-cpu-usage-in-linux-command-line
	#CPU=`top -bn3 -d0.5  | grep '^%Cpu' | tail -n2`

	#MEM=`free -h`

	STATS=`dstat -cmdnl 1 0`

	BATT=`acpi -b`
	TIME="`date` (update interval: $SLEEPTIME)"

	# clear right before writing new data to stdout
	# to avoid very noticeable flicker while stats are being generated
	clear

	#echo -e "$LOAD\n\n$CPU\n\n$MEM\n\n$BATT\n\n$TIME"
	#echo -e $STATS
	echo -e "$LOAD\n\n$STATS\n\n$BATT\n\n$TIME"

	sleep $SLEEPTIME
done
