#!/bin/bash
# Depends: notify.sh, vlc

[[ ($1 == "-h") || ($1 =~ "-help") ]] && echo "Usage: timer [NUM MINUTES] [AUDIO FILE TO PLAY]" && exit

if [ -z "$1" ]; then
	amt=300 # 5 minutes
else
	amt=$(($1*60))
fi

amtMinutes=$((amt/60))
echo "The time is now: $(date +%H:%M)"
echo -e "Timer will be done in $amtMinutes minute(s)\n\tat" $(date +%H:%M -d "$amtMinutes minutes") "("$(date +%F)")"

sleep $amt;
notify.sh "Timer for $amtMinutes min done";
[[ $2 ]] && vlc "$2" 2> /dev/null &
